os: linux
language: c++
services:
  - docker

stages:
  - name: static_checks
    if: branch != master AND branch != develop

before_script:
  - docker pull athenaml/build:latest

env:
  matrix:
    - ATHENA_BUILD_TYPE=Debug
    - ATHENA_BUILD_TYPE=Release

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export COMMAND_WRAPPER="docker run -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR -e ATHENA_TEST_ENVIRONMENT=ci -e ATHENA_BINARY_DIR=$TRAVIS_BUILD_DIR/install_$ATHENA_BUILD_TYPE -e CC=clang-8 -e CXX=clang++-8 athenaml/build"; fi
  - mkdir build_$ATHENA_BUILD_TYPE install_$ATHENA_BUILD_TYPE
  - $COMMAND_WRAPPER $TRAVIS_BUILD_DIR/scripts/build.py --build-type=$ATHENA_BUILD_TYPE $TRAVIS_BUILD_DIR/build_$ATHENA_BUILD_TYPE $TRAVIS_BUILD_DIR
  - $COMMAND_WRAPPER $TRAVIS_BUILD_DIR/scripts/build.py --build-type=$ATHENA_BUILD_TYPE $TRAVIS_BUILD_DIR/build_$ATHENA_BUILD_TYPE $TRAVIS_BUILD_DIR
  - $COMMAND_WRAPPER cmake --build $TRAVIS_BUILD_DIR/build_$ATHENA_BUILD_TYPE --target install
  - $COMMAND_WRAPPER $TRAVIS_BUILD_DIR/scripts/test.sh $TRAVIS_BUILD_DIR/build_$ATHENA_BUILD_TYPE

jobs:
  include:
    - stage: static_checks
      name: "Static Checks"
      env: ATHENA_BUILD_TYPE=Release
      script:
        - git fetch
        - docker run -v $TRAVIS_BUILD_DIR:/opt/src -e CLANG_FORMAT_DIFF_EXEC=/usr/lib/llvm-8/share/clang/clang-format-diff.py athenaml/build bash -c "cd /opt/src && scripts/clang-format.sh"
