name: Linux Checks

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container: athenaml/build:llvm10 
    strategy:
      matrix:
        build_type: ["Release", "Debug"]
        compiler: [["gcc", "g++"], ["clang", "clang++"]]

    steps:
      - uses: actions/checkout@v2
      - name: Configure
        env:
          CC: ${{ matrix.compiler[0] }}
          CXX: ${{ matrix.compiler[1] }}
        run: |
          mkdir -p build_${{ matrix.build_type }}
          mkdir -p install_${{ matrix.build_type }}
          ./scripts/build.py \
          --install_dir=${{ github.workspace }}/install_${{ matrix.build_type }} \
          --build_type=${{ matrix.build_type }} --ninja ${{ github.workspace }}
      - name: Build
        run: |
          cmake --build build_${{ matrix.build_type }} --target install
      - name: Test
        env:
          ATHENA_TEST_ENVIRONMENT: "ci"
        run: |
          cd build_${{ matrix.build }}
          ctest -VV -T Test
          
