name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: ["Release", "Debug"]

    steps:
      - uses: actions/checkout@v1
      - name: Prepare Env
        run: docker pull athenaml/build:llvm10
      - name: Test
        env:
          BUILD_TYPE: ${{ matrix.build_type }}
        run: $GITHUB_WORKSPACE/scripts/gh_ci_linux.sh
