name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: ["Release", "Debug"]

    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: |
          mkdir -p build_${{ matrix.build_type }}
          docker pull athenaml/build:latest
          export COMMAND_WRAPPER="docker run -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE -e ATHENA_TEST_ENVIRONMENT=ci -e ATHENA_BINARY_DIR=$GITHUB_WORKSPACE/install_${{ matrix.build_type }} -e CC=clang-8 -e CXX=clang++-8 athenaml/build"
          $COMMAND_WRAPPER $GITHUB_WORKSPACE/scripts/build.py --install-dir=$GITHUB_WORKSPACE/install_${{ matrix.build_type }} --build-type=${{ matrix.build_type }} $GITHUB_WORKSPACE/build_${{ matrix.build_type }} $GITHUB_WORKSPACE
          $COMMAND_WRAPPER cmake --build $GITHUB_WORKSPACE/build_${{ matrix.build_type }} --target install
          $COMMAND_WRAPPER $GITHUB_WORKSPACE/scripts/test.sh $GITHUB_WORKSPACE/build_${{ matrix.build_type }}
