name: PR review automation

on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Labeler
        uses: docker://decathlon/pull-request-labeler-action:2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  commit_message:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Check compliance with Conventional commits
        uses: docker://commitsar/commitsar:latest
